version: '3.8'
services:
  db:
    build:
      context: ./BD
      dockerfile: dockerfile
    volumes:
      - BD_data:/var/lib/postgresql/data
    networks:
      - monitoring_network
    ports:
      - "3001:5432"

  api:
    image: projetoescolar_api:latest
    container_name: api-1
    build:
      context: .
      dockerfile: dockerfile.app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app:app
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: escola
      DB_USER: admin
      DB_PASSWORD: admin123
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
